### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

**Comment by KatieMFritz** [comment]
First of all, fantastic content - I'm lol'ing, especially at the Alien Modelling Research tips. 😆 You also did a great job structuring this like a real resume! 💼 

### Make the image a clickable link to its source

As far as meeting the criteria: I see `h1`, `h2`, `p`, `img`, `ul`, and `li`, but no `a` (link). 

These are the criteria you're not meeting yet:
> * Each of the following elements is used appropriately, at least once: h1, h2, p, img, li, a
> * At least one external image is used and links to the page it came from

You can see how to create a link on [page 5 of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-atom-and-basic-elements/5) and how to make the image itself a clickable link under ["Making images clickable" on page 6](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-atom-and-basic-elements/6).

If you have any questions or get stuck, I'll be around! Good luck, ~~Peter~~ Spider Man. 😄

**Comment by amanuel1995** [comment]
Hey @KatieMFritz , thanks for the compliments... I just made up all the stuff. I had fun doing it. I have got a quick question for you; you said:  

"These are the criteria you're not meeting yet:
- Each of the following elements is used appropriately, at least once: h1, h2, p, img, li, a
- At least one external image is used and links to the page it came from"

I have used headers, paragraphs, image tag and lists. How do you mean using them appropriately then? (I think you didn't mean to add the first comment)

I will make the image clickable and link back to the original site where I got it from. Let me know if I should do more. Thank your for your review, it's thorough and I like it!

**Comment by KatieMFritz** [comment]
Hi Amanuel, making the image clickable will actually fix both problems - the only thing missing from that first bullet point is 'a' (link). The rest of those elements are indeed used appropriately! :smile:

Let me know when that's fixed and I'll take a look.

**Comment by amanuel1995** [comment]
I think I did it!

**Comment by KatieMFritz** [comment]
Code looks good, but don't forget to push to gh-pages as well!

**Comment by amanuel1995** [comment]
Did that too! Thank you!!

**Comment by KatieMFritz** [comment]
BOOM. :shipit:
